id: '74d3336e-f12a-49f6-737e-08dd7ccec69f'
name: 'C3-X-DB-FI '
description: 'This is my eLearning Project with the Databricks Stage Filegenerator to practice for the course C3-X-DB-DV'
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.Stage.Spark.Databricks.File'
  version: '1.8.0'
sourceSystems:
  - id: '8c1a2872-f80a-4dfe-812b-716864d05c1c'
    name: 'Adventure Works'
    description: 'This is the Source system for the Adventure Works parquet files'
    activeDiscovery: 'dc8901c1-4db3-474f-b4cc-bb7ee12a30ed'
    sourceSystemTypeId: 'c5e55725-184f-4c60-a22d-70cb5d6fe513'
propertyValues:
  - propertyId: '59eca19a-3bec-4169-85fd-41331f6fac3a'
    value: 'true'
  - propertyId: 'a9de64e6-8417-4f17-b491-4f105ed891a9'
    value: 'Sequential Notebook'
